name: PUSH) Backend ECS

on:
  push:
    paths:
      - backend/ecs/**
      - .github/workflows/backend_ecs.yml

jobs:
  ChatService:
    uses: ./.github/workflows/reuse_ecs.yml
    with:
      region: ap-northeast-1
      working-directory: backend/ecs/chat
      ECR_REPOSITORY: bedrock-chat
      ECS_CLUSTER_NAME: bedrock-cluster
      ECS_SERVICE_NAME: bedrock-chat
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  FunctionService:
    uses: ./.github/workflows/reuse_ecs.yml
    with:
      region: ap-northeast-1
      working-directory: backend/ecs/function
      ECR_REPOSITORY: bedrock-functions
      ECS_CLUSTER_NAME: bedrock-cluster
      ECS_SERVICE_NAME: bedrock-functions
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  RagService:
    uses: ./.github/workflows/reuse_ecs.yml
    with:
      region: ap-northeast-1
      working-directory: backend/ecs/rag
      ECR_REPOSITORY: bedrock-rag
      ECS_CLUSTER_NAME: bedrock-cluster
      ECS_SERVICE_NAME: bedrock-rag
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
