name: PUSH) Frontend

on:
  push:
    paths:
      - frontend/**
      - .github/workflows/frontend.yml
  workflow_run:
    workflows:
      - PUSH) Terraform
    branches:
      - master
    types:
      - completed

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  WORKING_DIRECTORY: frontend
  TERRAFORM_BACKEND_BUCKET_NAME: arms-terraform-0606
  TERRAFORM_BACKEND_BUCKET_KEY: bedrock/terraform.tfstate

jobs:
  Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      # Get terraform outputs
      - name: Get terraform outputs
        id: terraform
        run: |
          terraform init
          echo "bucket_name_frontend=$(terraform output -raw bucket_name_frontend)" >> $GITHUB_OUTPUT
          sh build.sh
          cat .env

      # Install and Build
      - name: Build
        run: |
          yarn install --production=false
          yarn build

      # Deploy frontend
      - name: Deploy
        env:
          BUCKET_NAME_FRONTEND: ${{ steps.terraform.outputs.bucket_name_frontend }}
        run: |
          aws s3 cp dist s3://$BUCKET_NAME_FRONTEND/ --recursive --region $AWS_DEFAULT_REGION
